(ns pangram
  (:require [clojure.string :as s]))

(defn pangram? [text]
  (= 26 (count (frequencies (re-seq #"[a-z]" (s/lower-case text))))))

(defn cursed-pangram? [st]
  (let [st2 (s/lower-case st)]
    (if (s/includes? st2 "a")
      (if (s/includes? st2 "b")
        (if (s/includes? st2 "c")
          (if (s/includes? st2 "d")
            (if (s/includes? st2 "e")
              (if (s/includes? st2 "f")
                (if (s/includes? st2 "g")
                  (if (s/includes? st2 "h")
                    (if (s/includes? st2 "i")
                      (if (s/includes? st2 "j")
                        (if (s/includes? st2 "k")
                          (if (s/includes? st2 "l")
                            (if (s/includes? st2 "m")
                              (if (s/includes? st2 "n")
                                (if (s/includes? st2 "o")
                                  (if (s/includes? st2 "p")
                                    (if (s/includes? st2 "q")
                                      (if (s/includes? st2 "r")
                                        (if (s/includes? st2 "s")
                                          (if (s/includes? st2 "t")
                                            (if (s/includes? st2 "u")
                                              (if (s/includes? st2 "v")
                                                (if (s/includes? st2 "w")
                                                  (if (s/includes? st2 "x")
                                                    (if (s/includes? st2 "y")
                                                      (if (s/includes? st2 "z")
                                                        true
                                                        false)
                                                      false)
                                                    false)
                                                  false)
                                                false)
                                              false)
                                            false)
                                          false)
                                        false)
                                      false)
                                    false)
                                  false)
                                false)
                              false)
                            false)
                          false)
                        false)
                      false)
                    false)
                  false)
                false)
              false)
            false)
          false)
        false)
      false)))
